/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'rounded-2xl', 'rounded-xl', 'rounded-lg', 'rounded-full',
    'shadow-xl', 'shadow-lg', 'shadow-md', 'shadow',
    'bg-white/90', 'bg-white/80', 'bg-white', 'bg-gray-50', 'bg-gradient-to-br', 'bg-gradient-to-b', 'bg-gradient-to-r',
    'backdrop-blur',
    'animate-fade-in-up', 'animate-fade-in',
    'border-2', 'border', 'border-gray-100', 'border-blue-200', 'border-green-400', 'border-red-300',
    'text-center', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl', 'text-6xl', 'text-lg', 'text-base', 'text-sm', 'text-xl',
    'font-bold', 'font-black', 'font-semibold',
    'mb-2', 'mb-4', 'mb-6', 'mb-8', 'mb-10', 'mb-12',
    'py-16', 'py-10', 'py-8', 'py-6', 'py-4', 'py-2', 'py-0',
    'px-4', 'px-6', 'px-8',
    'container', 'mx-auto',
    'drop-shadow-lg', 'drop-shadow-sm',
    'text-green-600', 'text-red-500', 'text-blue-700', 'text-gray-900', 'text-gray-700', 'text-gray-500', 'text-gray-400',
    'bg-green-400', 'bg-blue-400', 'bg-indigo-400', 'bg-purple-500', 'bg-orange-400', 'bg-yellow-400',
    'bg-blue-500', 'bg-green-500', 'bg-blue-600', 'bg-green-600', 'bg-slate-900',
    'hover:bg-blue-50', 'hover:from-green-600', 'hover:to-blue-600',
    'ring-2', 'ring-blue-400',
    'w-3', 'w-4', 'w-5', 'w-6', 'w-8', 'w-10', 'w-16',
    'h-3', 'h-4', 'h-5', 'h-6', 'h-8', 'h-10', 'h-16',
    'gap-2', 'gap-4', 'gap-6', 'gap-8', 'gap-10',
    'max-w-2xl', 'max-w-5xl',
    'p-6', 'p-8',
    'flex', 'items-center', 'justify-center', 'justify-between', 'flex-col', 'flex-row', 'space-x-2', 'space-x-3', 'space-x-4', 'space-y-4', 'space-y-6', 'space-y-8',
    'inline-flex', 'absolute', 'relative', 'fixed', 'top-24', 'top-28', 'right-4', 'right-6', 'z-50',
    'overflow-hidden', 'pointer-events-none', 'inset-0', 'z-0',
    'transition', 'transition-all', 'transition-colors', 'transition-transform', 'duration-200', 'duration-300', 'duration-500',
    'font-medium', 'font-semibold',
    'bg-clip-text', 'text-transparent',
    'border-white', 'border-gray-200', 'border-gray-700',
    'bg-slate-800', 'bg-slate-900', 'bg-blue-900',
    'mt-2', 'mt-4', 'mt-8', 'mt-10', 'mt-12', 'mt-16',
    'my-12', 'mb-16',
    'max-h-40', 'max-h-0',
    'overflow-hidden',
    'focus:outline-none',
    'hover:underline',
    'text-yellow-400',
    'text-white',
    'text-gray-600',
    'text-gray-400',
    'text-indigo-400',
    'text-blue-400',
    'text-green-400',
    'text-purple-500',
    'text-orange-400',
    'text-yellow-400',
    'bg-white/80',
    'shadow-2xl',
    'shadow-inner',
    'backdrop-blur-md',
    'bg-gradient-to-r',
    'from-green-400', 'from-green-500', 'from-blue-500', 'from-blue-600', 'from-slate-900',
    'via-blue-400', 'via-blue-500', 'via-blue-100', 'via-blue-900',
    'to-indigo-400', 'to-indigo-500', 'to-slate-800',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#22c55e',
          light: '#4ade80',
          dark: '#15803d',
        },
        accent: '#0ea5e9',
        indigo: '#6366f1',
        bg: '#f0f4f8',
        dark: '#18181b',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      boxShadow: {
        'wow': '0 8px 32px 0 rgba(34,197,94,0.15), 0 1.5px 6px 0 rgba(14,165,233,0.10)',
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #22c55e 0%, #0ea5e9 50%, #6366f1 100%)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.4,0,0.2,1) both',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

